# Exploring Our World in Data  COVID-19 data

Imports

In [1]:
import pandas as pd

Using the github download link we can pull the latest OWID COVID data straight from github

In [2]:
data_link = 'https://github.com/owid/covid-19-data/raw/master/public/data/owid-covid-data.csv'

df = pd.read_csv(data_link)

df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82284,ZWE,Africa,Zimbabwe,2021-04-13,37330.0,23.0,52.000,1543.0,1.0,1.714,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
82285,ZWE,Africa,Zimbabwe,2021-04-14,37369.0,39.0,55.000,1548.0,5.0,2.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
82286,ZWE,Africa,Zimbabwe,2021-04-15,37422.0,53.0,52.857,1550.0,2.0,2.571,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
82287,ZWE,Africa,Zimbabwe,2021-04-16,37534.0,112.0,55.286,1551.0,1.0,2.286,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
82288,ZWE,Africa,Zimbabwe,2021-04-17,37699.0,165.0,60.857,1552.0,1.0,2.000,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571

In [6]:
def get_length(string):
    return len(list(string))

In [7]:
country_df = df[df['iso_code'].apply(get_length) == 3]

In [10]:
country_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82284,ZWE,Africa,Zimbabwe,2021-04-13,37330.0,23.0,52.000,1543.0,1.0,1.714,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
82285,ZWE,Africa,Zimbabwe,2021-04-14,37369.0,39.0,55.000,1548.0,5.0,2.429,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
82286,ZWE,Africa,Zimbabwe,2021-04-15,37422.0,53.0,52.857,1550.0,2.0,2.571,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
82287,ZWE,Africa,Zimbabwe,2021-04-16,37534.0,112.0,55.286,1551.0,1.0,2.286,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571
82288,ZWE,Africa,Zimbabwe,2021-04-17,37699.0,165.0,60.857,1552.0,1.0,2.000,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571

In [ ]:
country_data_header = ['iso_code',
 'continent',
 'location',
 'population',
 'population_density',
 'median_age',
 'aged_65_older',
 'aged_70_older',
 'gdp_per_capita',
 'extreme_poverty',
 'cardiovasc_death_rate',
 'diabetes_prevalence',
 'female_smokers',
 'male_smokers',
 'handwashing_facilities',
 'hospital_beds_per_thousand',
 'life_expectancy',
 'human_development_index']

In [11]:
country_data = country_df.drop_duplicates(subset = 'location')



country_data

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.50,64.83,0.511
849,ALB,Europe,Albania,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,...,11803.431,1.1,304.195,10.08,7.1,51.2,NaN,2.89,78.57,0.795
1267,DZA,Africa,Algeria,2020-02-25,1.0,1.0,NaN,NaN,NaN,NaN,...,13913.839,0.5,278.364,6.73,0.7,30.4,83.741,1.90,76.88,0.748
1685,AND,Europe,Andorra,2020-03-02,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,109.135,7.97,29.0,37.8,NaN,NaN,83.73,0.868
2097,AGO,Africa,Angola,2020-03-20,1.0,1.0,NaN,NaN,NaN,NaN,...,5819.495,NaN,276.045,3.94,NaN,NaN,26.664,NaN,61.15,0.581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79823,VEN,South America,Venezuela,2020-03-14,2.0,2.0,NaN,NaN,NaN,NaN,...,16745.022,NaN,204.850,6.47,NaN,NaN,NaN,0.80,72.06,0.711
80223,VNM,Asia,Vietnam,2020-01-23,2.0,2.0,NaN,NaN,NaN,NaN,...,6171.884,2.0,245.465,6.00,1.0,45.9,85.847,2.60,75.40,0.704
81126,YEM,Asia,Yemen,2020-04-10,1.0,1.0,NaN,NaN,NaN,NaN,...,1479.147,18.8,495.003,5.35,7.6,29.2,49.542,0.70,66.12,0.470
81499,ZMB,Africa,Zambia,2020-03-18,2.0,2.0,NaN,NaN,NaN,NaN,...,3689.251,57.5,234.499,3.94,3.1,24.7,13.938,2.00,63.89,0.584
81895,ZWE,Africa,Zimbabwe,2020-03-20,1.0,1.0,NaN,NaN,NaN,NaN,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.70,61.49,0.571

In [12]:
list(df)

['iso_code',
 'continent',
 'location',
 'date',
 'total_cases',
 'new_cases',
 'new_cases_smoothed',
 'total_deaths',
 'new_deaths',
 'new_deaths_smoothed',
 'total_cases_per_million',
 'new_cases_per_million',
 'new_cases_smoothed_per_million',
 'total_deaths_per_million',
 'new_deaths_per_million',
 'new_deaths_smoothed_per_million',
 'reproduction_rate',
 'icu_patients',
 'icu_patients_per_million',
 'hosp_patients',
 'hosp_patients_per_million',
 'weekly_icu_admissions',
 'weekly_icu_admissions_per_million',
 'weekly_hosp_admissions',
 'weekly_hosp_admissions_per_million',
 'new_tests',
 'total_tests',
 'total_tests_per_thousand',
 'new_tests_per_thousand',
 'new_tests_smoothed',
 'new_tests_smoothed_per_thousand',
 'positive_rate',
 'tests_per_case',
 'tests_units',
 'total_vaccinations',
 'people_vaccinated',
 'people_fully_vaccinated',
 'new_vaccinations',
 'new_vaccinations_smoothed',
 'total_vaccinations_per_hundred',
 'people_vaccinated_per_hundred',
 'people_fully_vaccinated_per_hundred',
 'new_vaccinations_smoothed_per_million',
 'stringency_index',
 'population',
 'population_density',
 'median_age',
 'aged_65_older',
 'aged_70_older',
 'gdp_per_capita',
 'extreme_poverty',
 'cardiovasc_death_rate',
 'diabetes_prevalence',
 'female_smokers',
 'male_smokers',
 'handwashing_facilities',
 'hospital_beds_per_thousand',
 'life_expectancy',
 'human_development_index']

In [4]:
for i, j in enumerate(list(df)):
    print(i, ':', j)

0 : iso_code
1 : continent
2 : location
3 : date
4 : total_cases
5 : new_cases
6 : new_cases_smoothed
7 : total_deaths
8 : new_deaths
9 : new_deaths_smoothed
10 : total_cases_per_million
11 : new_cases_per_million
12 : new_cases_smoothed_per_million
13 : total_deaths_per_million
14 : new_deaths_per_million
15 : new_deaths_smoothed_per_million
16 : reproduction_rate
17 : icu_patients
18 : icu_patients_per_million
19 : hosp_patients
20 : hosp_patients_per_million
21 : weekly_icu_admissions
22 : weekly_icu_admissions_per_million
23 : weekly_hosp_admissions
24 : weekly_hosp_admissions_per_million
25 : new_tests
26 : total_tests
27 : total_tests_per_thousand
28 : new_tests_per_thousand
29 : new_tests_smoothed
30 : new_tests_smoothed_per_thousand
31 : positive_rate
32 : tests_per_case
33 : tests_units
34 : total_vaccinations
35 : people_vaccinated
36 : people_fully_vaccinated
37 : new_vaccinations
38 : new_vaccinations_smoothed
39 : total_vaccinations_per_hundred
40 : people_vaccinated_per_hundred
41 : people_fully_vaccinated_per_hundred
42 : new_vaccinations_smoothed_per_million
43 : stringency_index
44 : population
45 : population_density
46 : median_age
47 : aged_65_older
48 : aged_70_older
49 : gdp_per_capita
50 : extreme_poverty
51 : cardiovasc_death_rate
52 : diabetes_prevalence
53 : female_smokers
54 : male_smokers
55 : handwashing_facilities
56 : hospital_beds_per_thousand
57 : life_expectancy
58 : human_development_index